### ISSUE TITLE
Plugin setup

### ISSUE THREAD

**Issue by carlo318** [yangheng/cordova-plugin-serialPort#2]
Hi yangheng,
this is an interesting plugin.
I am trying to use it on a tablet having a hardware serial port.
I think you should add more information on how to setup the plugin.
In SerialPortActivity.java  I had to change:
`import com.ionicframework.starter.Application;`
with
`import [app.package].Application;`
to be coherent with  Application.java  package declaration.

Still, I cannot call openSerialPort(): it crashes in Java with no errors.
In the Readme it is written that the serial and baud rate are to be passed like this:
`.openSerialPort(device, baudRate, function success(data) , function error ());`
are you sure? 

Thankyou in advance.
Carlo

**Comment by carlo318** [comment]
The parameters for openSerialPort() are correct.
I found out that JNI libraries do not work with APP targeted Android API 23 or above.

Compiling with target Android API 22, solved my problem.

Thankyou.
Carlo

**Comment by yangheng** [comment]
Thank you for you feedback !
